# region FRONTIER - IGNORED
# If this changes, please update Resources\Prototypes\_NF\Recipes\Lathes\Packs\security.yml

# Base prototypes

- type: latheRecipe
  abstract: true
  id: BaseShieldRecipe
  categories:
  - Tools
  completetime: 4

- type: latheRecipe
  abstract: true
  id: BaseTargetRecipe
  categories:
  - Tools
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  abstract: true
  id: BaseWeaponRecipe
  categories:
  - Weapons

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeMelee
  completetime: 2

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipePractice
  completetime: 4

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeLong
  completetime: 5

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeSidearm
  completetime: 6

## Recipes

# Clothing
- type: latheRecipe
  id: ClothingEyesHudSecurity
  result: ClothingEyesHudSecurity
  categories:
  - Clothing
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: PortableRecharger
  result: PortableRecharger
  categories:
  - Clothing
  completetime: 15
  materials:
    Steel: 2000
    Uranium: 2000
    Plastic: 1000
    Plasma: 500
    Glass: 500

# Shields
- type: latheRecipe
  parent: BaseShieldRecipe
  id: RiotShield
  result: RiotShield
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  parent: BaseShieldRecipe
  id: TelescopicShield
  result: TelescopicShield
  materials:
    Steel: 300
    Glass: 800

# Targets

- type: latheRecipe
  parent: BaseTargetRecipe
  id: TargetClown
  result: TargetClown

# Tools
- type: latheRecipe
  parent: BaseToolRecipe
  id: Handcuffs
  result: Handcuffs
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseToolRecipe
  id: Zipties
  result: Zipties
  materials:
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipeMelee
  id: Katana
  result: Katana
  materials:
    Steel: 1000

- type: latheRecipe
  parent: BaseToolRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  parent: BaseToolRecipe
  id: HoloprojectorSecurity
  result: HoloprojectorSecurityEmpty
  materials:
    Steel: 300
    Glass: 50
    Plastic: 50

- type: latheRecipe
  parent: BaseToolRecipe
  id: Flash
  result: Flash
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

## Weapons

# Melee
- type: latheRecipe
  parent: BaseWeaponRecipeMelee
  id: Stunbaton
  result: Stunbaton
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  parent: BaseWeaponRecipeMelee
  id: Truncheon
  result: Truncheon
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  parent: BaseWeaponRecipeMelee
  id: CombatKnife
  result: CombatKnife
  materials:
    Steel: 250
    Plastic: 100

# Practice weapons
- type: latheRecipe
  parent: BaseWeaponRecipePractice
  id: WeaponDisablerPractice
  result: WeaponDisablerPractice
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipePractice
  id: WeaponLaserCarbinePractice
  result: WeaponLaserCarbinePractice
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250

# Long Guns
- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCarbine
  result: WeaponLaserCarbine
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponAdvancedLaser
  result: WeaponAdvancedLaser
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 850

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCannon
  result: WeaponLaserCannon
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponXrayCannon
  result: WeaponXrayCannon
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 100

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponTemperatureGun
  result: WeaponTemperatureGun
  materials:
    Steel: 2000
    Glass: 500
    Plastic: 500
    Gold: 500

- type: latheRecipe
  id: ClothingBackpackElectropack
  result: ClothingBackpackElectropack
  completetime: 4
  materials:
    Steel: 500
    Plastic: 250
    Cloth: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: AmmoBox12_gaugeTranquilizer
  result: AmmoBox12_gaugeTranquilizer
  materials:
    Plastic: 240
    Steel: 160
    Glass: 80
    Plasma: 160
    Silver: 80

- type: latheRecipe
  id: TargetHuman
  result: TargetHuman
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  parent: TargetHuman
  id: TargetSyndicate
  result: TargetSyndicate

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponFlareGunSecurity
  result: WeaponFlareGunSecurity
  completetime: 6
  materials:
    Plastic: 100
    Steel: 400

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponDisabler
  result: WeaponDisabler
  materials:
    Steel: 300
    Glass: 200
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponDisablerSMG
  result: WeaponDisablerSMG
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500

- type: latheRecipe
  id: Magazine40mmEmpty
  result: Magazine40mmEmpty
  completetime: 3
  materials:
    Steel: 150
    Plastic: 50

- type: latheRecipe
  id: 40mmGrenadeEMP
  result: 40mmGrenadeEMP
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

- type: latheRecipe
  id: 40mmGrenadeThermobaric
  result: 40mmGrenadeThermobaric
  completetime: 3
  materials:
    Steel: 450
    Plastic: 300
    Gold: 150

- type: latheRecipe
  id: 40mmGrenadeFlash
  result: 40mmGrenadeFlash
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

# mono changes end

# Shitmed Recipes

- type: latheRecipe
  id: SecurityCyberneticEyes
  result: SecurityCyberneticEyes
  completetime: 5
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500
    Gold: 300
    Silver: 300
