- type: entity
  id: BaseStation
  abstract: true
  components:
    - type: StationData

- type: entity
  id: BaseStationCargo
  abstract: true
  components:
    - type: StationBankAccount
    - type: StationCargoOrderDatabase
      orders:
        Cargo: [ ]
        Engineering: [ ]
        Medical: [ ]
        Science: [ ]
        Security: [ ]
        Service: [ ]
        Frontier: [ ]
        Nfsd: [ ]
    - type: StationCargoBountyDatabase

- type: entity
  id: BaseStationJobsSpawning
  abstract: true
  components:
    - type: StationJobs
      availableJobs: {}
    - type: StationSpawning

- type: entity
  id: BaseStationRecords
  abstract: true
  components:
    - type: StationRecords

- type: entity
  id: BaseStationArrivals
  abstract: true
  components:
    - type: StationArrivals

- type: entity
  id: BaseStationGateway
  abstract: true
  components:
    - type: GatewayGenerator

- type: entity
  id: BaseStationShuttles
  abstract: true
  components:
    - type: StationCargoShuttle
      path: /Maps/Shuttles/cargo.yml
    - type: GridSpawn
      groups:
        trade: !type:GridSpawnGroup
          addComponents:
            - type: ProtectedGrid
            - type: TradeStation
          paths:
            - /Maps/Shuttles/trading_outpost.yml
        # Spawn last
        ruins: !type:GridSpawnGroup
          hide: true
          nameGrid: true
          minCount: 2
          maxCount: 2
          stationGrid: false
          paths:
          - /Maps/Ruins/abandoned_outpost.yml
          - /Maps/Ruins/chunked_tcomms.yml
          - /Maps/Ruins/biodome_satellite.yml
          - /Maps/Ruins/derelict.yml
          - /Maps/Ruins/djstation.yml
          - /Maps/Ruins/empty_flagship.yml
          - /Maps/Ruins/hydro_outpost.yml
          - /Maps/Ruins/old_ai_sat.yml
          - /Maps/Ruins/ruined_prison_ship.yml
          - /Maps/Ruins/syndicate_dropship.yml
          - /Maps/Ruins/whiteship_ancient.yml
          - /Maps/Ruins/whiteship_bluespacejumper.yml
          - /Maps/Ruins/wrecklaimer.yml
        # vgroid: !type:DungeonSpawnGroup # Frontier
          # minimumDistance: 300 # Frontier
          # maximumDistance: 350 # Frontier
          # nameDataset: NamesBorer # Frontier
          # stationGrid: false # Frontier
          # addComponents: # Frontier
          # - type: Gravity # Frontier
            # enabled: true # Frontier
            # inherent: true # Frontier
          # protos: # Frontier
          # - VGRoid # Frontier

- type: entity
  id: BaseStationColcomm
  abstract: true
  components:
    - type: StationColcomm

- type: entity
  id: BaseStationEvacuation
  abstract: true
  components:
    - type: StationEmergencyShuttle

- type: entity
  id: BaseStationAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: stationAlerts

- type: entity
  id: BaseStationExpeditions
  abstract: true
  components:
    - type: SalvageExpeditionData

- type: entity
  id: BaseStationMagnet
  abstract: true
  components:
    - type: SalvageMagnetData

- type: entity
  id: BaseStationSiliconLawCrewsimov
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Crewsimov

- type: entity
  id: BaseStationNews
  abstract: true
  components:
    - type: StationNews

- type: entity
  id: BaseStationDeliveries
  abstract: true
  components:
  - type: CargoDeliveryData

- type: entity
  id: BaseStationAllEventsEligible
  abstract: true
  components:
    - type: StationEventEligible # For when someone makes this more granular in the future.

- type: entity
  id: BaseStationSiliconLawFrontierStation
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: NTDefault

- type: entity
  id: BaseStationSiliconLawFrontierShips
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Corporate

- type: entity
  id: BaseStationRenameFaxes
  abstract: true
  components:
  - type: StationRenameFaxes

- type: entity
  id: BaseStationRenameHolopads
  abstract: true
  components:
  - type: StationRenameHolopads

- type: entity
  id: BaseStationRenameWarpPoints
  abstract: true
  components:
  - type: StationRenameWarps

# Sector-wide news access, should be on stations with comms (radio station, telecomms)
# TODO: move SectorNewsComponent to a SectorService
- type: entity
  id: BaseStationSectorNews
  abstract: true
  components:
  - type: SectorNews

# Uses this station ID to host singleton-esque services to avoid station references (e.g. for PDA apps)
- type: entity
  id: BaseStationSectorServices
  abstract: true
  components:
  - type: StationSectorServiceHost

- type: entity
  id: BaseStationDampening
  abstract: true
  components:
  - type: StationDampening

- type: entity
  id: NFBaseStationCargo
  abstract: true
  components:
    - type: NFStationCargoOrderDatabase

- type: entity
  id: BaseStationCargoMarket
  abstract: true
  components:
  - type: CargoMarketData
    whitelist:
      tags:
      - Ore
      - Sheet
      - Metal
      - Ingot
      - RawMaterial
      - CrystalRed
      - CrystalGreen
      - CrystalPink
      - CrystalOrange
      - CrystalBlue
      - CrystalCyan
      components:
      - Material
      - ConstructionMaterials
      - ToolRefinable
      - MachinePart
      - VendingMachineRestock
      - Seed
      - MachineBoard
      - ComputerBoard
    blacklist:
      tags:
      - Trash
      - Mail
      - Paper
      components:
      - Anchorable # No structures, they won't fit in crates
      - Food
      - Currency # No selling money.
      - SpaceGarbage
      - Contraband
      - Gun
      - Ammo
      - Drink
      - GasTank # Default containers won't be empty
      - Explosive
      - Actor
      - Mind # Players
      - MindContainer # Positronic brains
      - Body # No corpses
      - MobPrice # Animals (live or dead) and the like
      - Artifact # Unique, abusable for research points
      - RCD # Dup charges
      - Storage # Till fixed
      - StorageFill # Till fixed
      - BindToStation # no laundering your rental ship machines
    whitelistOverride:
      components:
      - UraniumMaterials # Counts as food

- type: entity
  id: BaseStationDeadDrops
  abstract: true
  components:
    - type: StationDeadDrop
      maxDeadDrops: 2 # A few to be stumbled upon.

- type: entity
  id: BaseStationDeadDropHintExempt
  abstract: true
  components:
    - type: StationDeadDropHintExempt

- type: entity
  id: BaseStationBusDepot
  abstract: true
  components:
  - type: StationBusDepot

